"""Train a HistGradientBoostingRegressor for HVAC setpoint recommendation.

The target is an energy-aware, comfort-constrained setpoint. It is generated by
scoring candidate setpoints with an estimated HVAC energy cost, comfort penalty,
and setpoint-change penalty. This gives the visualization app a fast tabular
alternative to the sequence Transformer.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from energy_aware_target import (
    SETPOINT_MAX,
    SETPOINT_MIN,
    energy_aware_recommended_setpoints,
    target_diagnostics,
)


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "Data"
OUT = Path(__file__).resolve().parent

SEED = 42

USECOLS = [
    "timestamp",
    "room_number",
    "floor",
    "facade",
    "room_type",
    "size_m2",
    "outside_temp",
    "room_temp",
    "setpoint",
    "ideal_temp",
    "hvac_mode",
    "ac_persona",
    "occupant_state",
    "pir_persona",
    "room_state",
    "pir_motion",
    "guest_id",
]

NUMERIC_FEATURES = [
    "floor_scaled",
    "size_scaled",
    "outside_temp_scaled",
    "room_temp_scaled",
    "setpoint_scaled",
    "ideal_temp_scaled",
    "temp_error_scaled",
    "comfort_error_scaled",
    "pir_motion",
    "has_guest",
    "hour_sin",
    "hour_cos",
    "dow_sin",
    "dow_cos",
]

CATEGORICAL_FEATURES = [
    "facade",
    "room_type",
    "hvac_mode",
    "occupant_state",
    "pir_persona",
    "occupancy_prediction",
    "temperature_persona_prediction",
]

def _cyclic(series: pd.Series, period: int) -> tuple[pd.Series, pd.Series]:
    radians = 2 * np.pi * series / period
    return np.sin(radians), np.cos(radians)


def _scale_temp(series: pd.Series) -> pd.Series:
    values = pd.to_numeric(series, errors="coerce").fillna(0).clip(-20, 50)
    return (values + 20) / 70


def build_features(max_rows: int | None = None) -> pd.DataFrame:
    df = pd.read_csv(
        DATA / "temperatureData.csv",
        usecols=USECOLS,
        parse_dates=["timestamp"],
        nrows=max_rows,
    )
    df = df.dropna(subset=["timestamp"]).copy()
    df = df.sort_values(["room_number", "timestamp"]).reset_index(drop=True)

    for col in ["floor", "size_m2", "outside_temp", "room_temp", "setpoint", "ideal_temp", "pir_motion"]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)
    df["guest_id"] = pd.to_numeric(df["guest_id"], errors="coerce")

    df["occupancy_prediction"] = df["room_state"].fillna("Unknown").astype(str)
    df["temperature_persona_prediction"] = df["ac_persona"].fillna("Unknown").astype(str)
    for col in CATEGORICAL_FEATURES:
        df[col] = df[col].fillna("Unknown").astype(str)

    df["floor_scaled"] = df["floor"].clip(0, 30) / 30.0
    df["size_scaled"] = df["size_m2"].clip(0, 120) / 120.0
    df["outside_temp_scaled"] = _scale_temp(df["outside_temp"])
    df["room_temp_scaled"] = _scale_temp(df["room_temp"])
    df["setpoint_scaled"] = _scale_temp(df["setpoint"])
    df["ideal_temp_scaled"] = _scale_temp(df["ideal_temp"])
    df["temp_error_scaled"] = ((df["room_temp"] - df["setpoint"]).clip(-20, 20) + 20) / 40.0
    df["comfort_error_scaled"] = ((df["room_temp"] - df["ideal_temp"]).clip(-20, 20) + 20) / 40.0
    df["pir_motion"] = df["pir_motion"].clip(0, 1).astype("float32")
    df["has_guest"] = df["guest_id"].notna().astype("float32")
    df["hour_sin"], df["hour_cos"] = _cyclic(df["timestamp"].dt.hour, 24)
    df["dow_sin"], df["dow_cos"] = _cyclic(df["timestamp"].dt.dayofweek, 7)

    for col in NUMERIC_FEATURES:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype("float32")

    df["recommended_setpoint"] = energy_aware_recommended_setpoints(df)
    return df.reset_index(drop=True)


def add_energy_diagnostics(frame: pd.DataFrame, recommended: np.ndarray | pd.Series) -> pd.DataFrame:
    rows = []
    for (_, row), rec in zip(frame.iterrows(), recommended):
        rows.append(target_diagnostics(row, float(rec)))
    return pd.DataFrame(rows, index=frame.index)


def train(max_rows: int | None = None, output_dir: Path = OUT) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    model_file = output_dir / "tempreture_recomendation_hgb_model.joblib"
    report_file = output_dir / "tempreture_recomendation_hgb_report.txt"
    predictions_file = output_dir / "tempreture_recomendation_hgb_sample_predictions.csv"
    metadata_file = output_dir / "tempreture_recomendation_hgb_metadata.json"

    df = build_features(max_rows=max_rows)

    split_time = df["timestamp"].quantile(0.80)
    train_df = df[df["timestamp"] <= split_time].copy()
    test_df = df[df["timestamp"] > split_time].copy()

    x_train = train_df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
    y_train = train_df["recommended_setpoint"]
    x_test = test_df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
    y_test = test_df["recommended_setpoint"]

    model = Pipeline(
        steps=[
            (
                "preprocessor",
                ColumnTransformer(
                    transformers=[
                        (
                            "num",
                            Pipeline(
                                steps=[
                                    ("imputer", SimpleImputer(strategy="median")),
                                    ("scaler", StandardScaler()),
                                ]
                            ),
                            NUMERIC_FEATURES,
                        ),
                        (
                            "cat",
                            Pipeline(
                                steps=[
                                    ("imputer", SimpleImputer(strategy="most_frequent")),
                                    ("onehot", OneHotEncoder(handle_unknown="ignore")),
                                ]
                            ),
                            CATEGORICAL_FEATURES,
                        ),
                    ]
                ),
            ),
            (
                "regressor",
                HistGradientBoostingRegressor(
                    max_iter=220,
                    learning_rate=0.07,
                    max_leaf_nodes=31,
                    l2_regularization=0.01,
                    random_state=SEED,
                ),
            ),
        ]
    )

    model.fit(x_train, y_train)
    pred = np.clip(model.predict(x_test), SETPOINT_MIN, SETPOINT_MAX)
    pred = np.round(pred * 2) / 2

    mae = mean_absolute_error(y_test, pred)
    rmse = float(np.sqrt(mean_squared_error(y_test, pred)))
    r2 = r2_score(y_test, pred)
    target_diag = add_energy_diagnostics(test_df, y_test.to_numpy())
    model_diag = add_energy_diagnostics(test_df, pred)
    current_energy_proxy = float(target_diag["current_power_w"].sum())
    target_energy_proxy = float(target_diag["target_power_w"].sum())
    model_energy_proxy = float(model_diag["target_power_w"].sum())
    target_saving_pct = 100 * (1 - target_energy_proxy / current_energy_proxy) if current_energy_proxy else 0.0
    model_saving_pct = 100 * (1 - model_energy_proxy / current_energy_proxy) if current_energy_proxy else 0.0
    target_comfort_gap = float(target_diag["target_comfort_gap_c"].mean())
    model_comfort_gap = float(model_diag["target_comfort_gap_c"].mean())

    comparison = test_df[
        [
            "timestamp",
            "room_number",
            "room_temp",
            "setpoint",
            "ideal_temp",
            "outside_temp",
            "hvac_mode",
            "occupancy_prediction",
            "temperature_persona_prediction",
        ]
    ].copy()
    comparison["recommended_target"] = y_test.to_numpy()
    comparison["model_prediction"] = pred
    comparison["target_mode"] = target_diag["target_mode"].to_numpy()
    comparison["current_power_w"] = target_diag["current_power_w"].to_numpy()
    comparison["target_power_w"] = target_diag["target_power_w"].to_numpy()
    comparison["model_power_w"] = model_diag["target_power_w"].to_numpy()
    comparison.head(5000).to_csv(predictions_file, index=False)

    metadata = {
        "model_type": "hist_gradient_boosting_regressor",
        "task": "tempreture_recomendation",
        "prediction_horizon_minutes": 5,
        "target": "recommended_setpoint",
        "target_strategy": "energy_aware_comfort_constrained",
        "setpoint_min": SETPOINT_MIN,
        "setpoint_max": SETPOINT_MAX,
        "numeric_features": NUMERIC_FEATURES,
        "categorical_features": CATEGORICAL_FEATURES,
        "seed": SEED,
        "max_rows": max_rows,
        "output_dir": str(output_dir),
        "metrics": {
            "mae": float(mae),
            "rmse": float(rmse),
            "r2": float(r2),
            "target_saving_pct": float(target_saving_pct),
            "model_saving_pct": float(model_saving_pct),
            "target_mean_comfort_gap_c": float(target_comfort_gap),
            "model_mean_comfort_gap_c": float(model_comfort_gap),
        },
    }
    joblib.dump(
        {
            "model": model,
            "feature_columns": NUMERIC_FEATURES + CATEGORICAL_FEATURES,
            "numeric_features": NUMERIC_FEATURES,
            "categorical_features": CATEGORICAL_FEATURES,
            "metadata": metadata,
        },
        model_file,
    )
    metadata_file.write_text(json.dumps(metadata, indent=2))

    report = "\n".join(
        [
            f"rows: {len(df):,}",
            f"train rows: {len(train_df):,}",
            f"test rows: {len(test_df):,}",
            f"split time: {split_time}",
            "algorithm: HistGradientBoostingRegressor",
            "target strategy: energy-aware comfort-constrained setpoint",
            f"MAE: {mae:.3f}",
            f"RMSE: {rmse:.3f}",
            f"R2: {r2:.3f}",
            f"current energy proxy W-sum: {current_energy_proxy:.0f}",
            f"target energy proxy W-sum: {target_energy_proxy:.0f}",
            f"model energy proxy W-sum: {model_energy_proxy:.0f}",
            f"target saving vs current: {target_saving_pct:.2f}%",
            f"model saving vs current: {model_saving_pct:.2f}%",
            f"target mean comfort gap C: {target_comfort_gap:.3f}",
            f"model mean comfort gap C: {model_comfort_gap:.3f}",
        ]
    )
    report_file.write_text(report)
    print(report)
    print(f"\nsaved {report_file}")
    print(f"saved {predictions_file}")
    print(f"saved {model_file}")
    print(f"saved {metadata_file}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-rows", type=int, default=None)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUT,
        help="Artifact directory. Defaults to the app's HGB model folder.",
    )
    args = parser.parse_args()
    train(max_rows=args.max_rows, output_dir=args.output_dir)


if __name__ == "__main__":
    main()
